backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

site_url: https://hrpci.org
display_url: https://hrpci.org

collections:
  - name: "pages"
    label: "Website Pages"
    folder: "/"
    create: false
    delete: false
    format: "frontmatter"
    extension: "html"
    fields:
      - { label: "Page Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "homepage"
    label: "Homepage Sections"
    files:
      - label: "Home Content"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Page Title", name: "title", widget: "string" }
          - { label: "Main Content", name: "body", widget: "markdown" }

  - name: "images"
    label: "Images"
    folder: "assets/uploads"
    create: true
    delete: true
    fields:
      - { label: "Image", name: "image", widget: "image" }
