backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Website Pages"
    files:
      - label: "Home Page"
        name: "index"
        file: "index.html"
        fields:
          - {label: "Content", name: "body", widget: "markdown"}

      - label: "About Page"
        name: "about"
        file: "about.html"
        fields:
          - {label: "Content", name: "body", widget: "markdown"}

      - label: "Awards Page"
        name: "awards"
        file: "awards.html"
        fields:
          - {label: "Content", name: "body", widget: "markdown"}

      - label: "Contact Page"
        name: "contact"
        file: "contact.html"
        fields:
          - {label: "Content", name: "body", widget: "markdown"}

      - label: "Honorary Doctorate Page"
        name: "honorary-doctorate"
        file: "honorary-doctorate.html"
        fields:
          - {label: "Content", name: "body", widget: "markdown"}
